const mongoose = require("mongoose");

//define a comment schema for the database
const CommentSchema = new mongoose.Schema({
  creator_id: String,
  creator_name: String,
  timestamp: { type: Date, default: Date.now },
  parent: String, // links to the _id of a parent workout (_id is an autogenerated field by Mongoose).
  content: String,
});

// compile model from schema
module.exports = mongoose.model("comment", CommentSchema);
